<?php
/**
 * PHP functions for MODULE
 */

 /**
 * Implements hook_theme().
 */
function du_events_theme($existing, $type, $theme, $path) {
  return [
    'node__event' => [
      'template' => 'node--event',
      'base hook' => 'node',
    ],
    'paragraph__event_list' => [
      'template' => 'paragraph--event_list',
      'base hook' => 'paragraph',
    ],
    'paragraph__event_time_place' => [
      'template' => 'paragraph--event_time_place',
      'base hook' => 'paragraph',
    ],
    'taxonomy_term__event_audiences' => [
      'template' => 'taxonomy-term--event-audiences',
      'base hook' => 'taxonomy_term',
    ],
    'taxonomy_term__event_types' => [
      'template' => 'taxonomy-term--event-types',
      'base hook' => 'taxonomy_term',
    ],
    'views_view_fields__event_list__mini' => [
      'template' => 'views-view-fields--event-list--mini',
      'base hook' => 'views_view_fields',
    ],
    'views_view_fields__event_list' => [
      'template' => 'views-view-fields--event-list',
      'base hook' => 'views_view_fields',
    ],
    'views_view_unformatted__event_list__mini' => [
      'template' => 'views-view-unformatted--event-list--mini',
      'base hook' => 'views_view_unformatted',
    ],
    'views_view_unformatted__event_list' => [
      'template' => 'views-view-unformatted--event-list',
      'base hook' => 'views_view_unformatted',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 */
function du_events_preprocess_paragraph__event_list(&$variables) {
  $variables['#attached']['library'][] = 'du_events/events';
}

/**
 * Implements hook_preprocess_node().
 */
function du_events_preprocess_node(&$variables) {
  if ($variables['node']->getType() === 'event') {
    $variables['#attached']['library'][] = 'du_events/events';
  }
}

