<?php

declare(strict_types=1);

namespace Drupal\Tests\du_event_display\Unit\Calendar;

use Drupal\du_event_display\Calendar\CalendarEvent;
use Drupal\Tests\UnitTestCase;

/**
 * Tests the CalendarEvent class.
 *
 * @group du_event_display
 * @coversDefaultClass \Drupal\du_event_display\Calendar\CalendarEvent
 */
final class CalendarEventTest extends UnitTestCase {

  /**
   * Creates a mock field value object.
   *
   * The CalendarEvent::formatValue() method expects objects with a 'value'
   * property, similar to Drupal field items.
   *
   * @param string $value
   *   The string value.
   *
   * @return object
   *   An object with a value property.
   */
  private function createFieldValue(string $value): object {
    $obj = new \stdClass();
    $obj->value = $value;
    return $obj;
  }

  /**
   * Tests constructor with custom UID.
   *
   * @covers ::__construct
   */
  public function testConstructorWithCustomUid(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'custom-uid-123',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Test Event'),
      'description' => $this->createFieldValue('Test Description'),
      'location' => 'Test Location',
    ]);

    $output = $event->generateString();
    self::assertStringContainsString('UID:custom-uid-123', $output);
  }

  /**
   * Tests constructor generates UID when not provided.
   *
   * @covers ::__construct
   */
  public function testConstructorGeneratesUidWhenNotProvided(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Test Event'),
      'description' => $this->createFieldValue('Test Description'),
    ]);

    $output = $event->generateString();
    self::assertStringContainsString('UID:', $output);
  }

  /**
   * Tests that two events get different auto-generated UIDs.
   *
   * @covers ::__construct
   */
  public function testAutoGeneratedUidsAreUnique(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event1 = new CalendarEvent([
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Event 1'),
      'description' => $this->createFieldValue(''),
    ]);

    $event2 = new CalendarEvent([
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Event 2'),
      'description' => $this->createFieldValue(''),
    ]);

    $output1 = $event1->generateString();
    $output2 = $event2->generateString();

    // Extract UIDs from output.
    preg_match('/UID:([^\r\n]+)/', $output1, $matches1);
    preg_match('/UID:([^\r\n]+)/', $output2, $matches2);

    self::assertNotEquals($matches1[1], $matches2[1]);
  }

  /**
   * Tests generateString returns valid VEVENT format.
   *
   * @covers ::generateString
   */
  public function testGenerateStringReturnsValidVeventFormat(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'test-uid',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Test Event'),
      'description' => $this->createFieldValue('Test Description'),
      'location' => 'Test Location',
    ]);

    $output = $event->generateString();

    self::assertStringContainsString('BEGIN:VEVENT', $output);
    self::assertStringContainsString('END:VEVENT', $output);
    self::assertStringContainsString('UID:test-uid', $output);
    self::assertStringContainsString('DTSTART:', $output);
    self::assertStringContainsString('DTEND:', $output);
    self::assertStringContainsString('DTSTAMP:', $output);
    self::assertStringContainsString('CREATED:', $output);
    self::assertStringContainsString('LAST-MODIFIED:', $output);
    self::assertStringContainsString('SEQUENCE:0', $output);
    self::assertStringContainsString('STATUS:CONFIRMED', $output);
    self::assertStringContainsString('TRANSP:OPAQUE', $output);
  }

  /**
   * Tests generateString includes event details.
   *
   * @covers ::generateString
   */
  public function testGenerateStringIncludesEventDetails(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'test-uid',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('My Event Title'),
      'description' => $this->createFieldValue('My event description'),
      'location' => 'Conference Room A',
    ]);

    $output = $event->generateString();

    self::assertStringContainsString('SUMMARY:My Event Title', $output);
    self::assertStringContainsString('DESCRIPTION:My event description', $output);
    self::assertStringContainsString('LOCATION:Conference Room A', $output);
  }

  /**
   * Tests date formatting in generateString.
   *
   * @covers ::generateString
   */
  public function testDateFormatting(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:30:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'test-uid',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Test Event'),
      'description' => $this->createFieldValue(''),
    ]);

    $output = $event->generateString();

    self::assertStringContainsString('DTSTART:20240115T100000Z', $output);
    self::assertStringContainsString('DTEND:20240115T113000Z', $output);
  }

  /**
   * Tests that commas are escaped in summary.
   *
   * @covers ::generateString
   */
  public function testCommasAreEscaped(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'test-uid',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Event with, comma'),
      'description' => $this->createFieldValue('Description with, comma'),
    ]);

    $output = $event->generateString();

    self::assertStringContainsString('SUMMARY:Event with\\, comma', $output);
    self::assertStringContainsString('DESCRIPTION:Description with\\, comma', $output);
  }

  /**
   * Tests that semicolons are escaped.
   *
   * @covers ::generateString
   */
  public function testSemicolonsAreEscaped(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'test-uid',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Event; with semicolon'),
      'description' => $this->createFieldValue(''),
    ]);

    $output = $event->generateString();

    self::assertStringContainsString('SUMMARY:Event\\; with semicolon', $output);
  }

  /**
   * Tests that backslashes are escaped.
   *
   * @covers ::generateString
   */
  public function testBackslashesAreEscaped(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'test-uid',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Event with \\ backslash'),
      'description' => $this->createFieldValue(''),
    ]);

    $output = $event->generateString();

    self::assertStringContainsString('SUMMARY:Event with \\\\ backslash', $output);
  }

  /**
   * Tests empty location is handled.
   *
   * @covers ::generateString
   */
  public function testEmptyLocation(): void {
    $start = new \DateTime('2024-01-15 10:00:00', new \DateTimeZone('UTC'));
    $end = new \DateTime('2024-01-15 11:00:00', new \DateTimeZone('UTC'));

    $event = new CalendarEvent([
      'uid' => 'test-uid',
      'start' => $start,
      'end' => $end,
      'summary' => $this->createFieldValue('Test Event'),
      'description' => $this->createFieldValue(''),
    ]);

    $output = $event->generateString();

    // Location should be present but empty.
    self::assertStringContainsString('LOCATION:', $output);
  }

}
