name: DU Events Install Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout module
        uses: actions/checkout@v4
        with:
            path: du_events

      - name: Checkout Drupal upstream
        uses: actions/checkout@v4
        with:
          repository: DU-University-Relations/drupal-composer-managed
          path: upstream
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          ddevDir: upstream

      - name: Install Drupal with Profile
        working-directory: upstream
        run: |
          # Install dependencies
          ddev composer install

          # Add module code from PR to site as a CUSTOM module to override the contrib version of the same module
          mkdir -p web/modules/custom
          cp -r ../du_events web/modules/custom/du_events

      - name: Copy and include default/settings.php
        working-directory: upstream
        run: |
          cp web/sites/default/default.settings.php web/sites/default/settings.php
          echo "include \$app_root . '/' . \$site_path . '/settings.local.php';" >> web/sites/default/settings.php

      - name: Install site
        working-directory: upstream
        run: |
          ddev exec drush site:install ducore \
            --account-name=admin \
            --account-pass=admin \
            --site-name="Test Site" \
            --yes

      - name: Install du_events
        working-directory: upstream
        run: |
          ddev exec drush en du_events
          ddev exec drush cr